### ISSUE TITLE
目前无法启动stable diffusion（无法导入_compare_version）

### ISSUE THREAD

**Issue by Mira-LeafTown** [AI-skimos/3line-colab-sd#7]
报错内容:
Launching Web UI with arguments: --listen --share --xformers --enable-insecure-extension-access --theme dark --clip-models-path /content/drive/MyDrive/SD/models/CLIP
2023-07-09 12:07:01.383771: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-09 12:07:02.723237: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/content/drive/MyDrive/SD/launch.py", line 382, in <module>
    start()
  File "/content/drive/MyDrive/SD/launch.py", line 372, in start
    import webui
  File "/content/drive/MyDrive/SD/webui.py", line 28, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/drive/MyDrive/SD/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/drive/MyDrive/SD/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/drive/MyDrive/SD/modules/sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/drive/MyDrive/SD/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 12, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/progress/rich_progress.py", line 20, in <module>
    from torchmetrics.utilities.imports import _compare_version
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (/usr/local/lib/python3.10/dist-packages/torchmetrics/utilities/imports.py)

**Comment by Mira-LeafTown** [comment]
已知的解决办法就是把torchmetrics的版本换成0.11.4

**Comment by fukanon** [comment]
怎么改，改哪里，大佬，求教

**Comment by DeadBoy2537** [comment]
> 

fork一下这个仓库，然后自己修改一下脚本，在脚本223行处新开一行，加入pip install torchmetrics==0.11.4

**Comment by Mira-LeafTown** [comment]
> 怎么改，改哪里，大佬，求教

fork一下这个仓库，然后自己修改一下脚本，在脚本223行处新开一行，加入pip install torchmetrics==0.11.4
